replicaCount: 1

name: dondevil-de

image:
  repository: harbor.fayevr.dev/fleet/dondevil-de
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
  hosts:
    - host: dondevil.de
      paths:
        - path: "/"
          pathType: Prefix
    - host: www.dondevil.de
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - dondevil.de
        - www.dondevil.de
      secretName: dondevil-de-tls-secret

secrets:
  name: dondevil-de-variables
  imagePullSecrets:
    - name: harbor-secret

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "100m"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"

probes:
  liveness:
    path: "/"
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readiness:
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

pdb:
  enabled: false
  minAvailable: 1
