replicaCount: 1

name: phc-website

image:
  repository: harbor.fayevr.dev/fleet/phc-website
  tag: "0.1.1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: preview.phc.fayevr.dev
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - preview.phc.fayevr.dev
      secretName: phc-website-tls

# PostgreSQL Database Configuration
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  database:
    name: phc
    user: postgres
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "100m"

# Database URL for the application
database:
  url: "postgresql://postgres:{{ .Values.postgresql.database.password }}@{{ .Values.name }}-postgres:5432/{{ .Values.postgresql.database.name }}"

secrets:
  name: phc-website-variables
  imagePullSecrets:
    - name: harbor-secret

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "100m"
