{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-postgres-secret
  labels:
    app: {{ .Values.name }}-postgres
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc }}
{{- end }} 