{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: phc-website-proxy-headers
data:
  Host: "preview.phc.fayevr.dev"
  X-Forwarded-Host: "preview.phc.fayevr.dev"
  X-Forwarded-Proto: "https"
{{- end }} 