apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-bot
  labels:
    app: {{ .Values.name }}-bot
spec:
  selector:
    app: {{ .Values.name }}-bot
  ports:
    - name: internal-api
      protocol: TCP
      port: {{ .Values.bot.port }}
      targetPort: internal-api
  type: ClusterIP
