apiVersion: v2
name: suggestions-bot
description: A Helm chart for deploying suggestions-bot
version: 1.1.2
type: application

dependencies:
  - name: redis
    version: 23.2.12
    repository: oci://registry-1.docker.io/bitnamicharts
