replicaCount: 1

name: suggestions-bot

image:
  repository: harbor.fayevr.dev/fleet/suggestions-bot
  tag: "1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: suggestions.fayevr.dev
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - suggestions.fayevr.dev
      secretName: suggestions-bot-tls

secrets:
  name: suggestions-bot-variables
  imagePullSecrets:
    - name: harbor-secret

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "100m"

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: true # Password authentication
  architecture: standalone
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
  service:
    type: ClusterIP
    port: 6379
