replicaCount: 1

name: suggestions-bot

image:
  repository: harbor.fayevr.dev/fleet/suggestions-bot
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

secrets:
  name: suggestions-bot-variables
  imagePullSecrets:
    - name: harbor-secret

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "100m"

probes:
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

pdb:
  enabled: false
  minAvailable: 1

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: true # Password authentication
  architecture: standalone
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
  service:
    type: ClusterIP
    port: 6379
