replicaCount: 1

name: mexi-fayevr-dev

image:
  repository: harbor.fayevr.dev/fleet/modmail-bot
  tag: "mexify"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: mexi.fayevr.dev
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - mexi.fayevr.dev
      secretName: mexi-fayevr-tls

secrets:
  name: mexi-fayevr-variables
  imagePullSecrets:
    - name: harbor-secret

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "100m"

probes:
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

pdb:
  enabled: false
  minAvailable: 1
