replicaCount: 1

name: headpat-space

image:
  repository: harbor.fayevr.dev/fleet/headpat-space
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: headpat.space
      paths:
        - path: "/"
          pathType: Prefix
    - host: www.headpat.space
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - headpat.space
        - www.headpat.space
      secretName: headpat-space-tls

secrets:
  name: headpat-space-variables
  imagePullSecrets:
    - name: harbor-secret

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "100m"
